#
# This file is part of the nspanelMqttBridge distribution (https://github.com/olialb/nspanelMqttBridge).
# Copyright (c) 2026 Oliver Albold.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
[global]
#set server ip adress and port
broker=192.168.1.31
port=1883
#set username and password if needed:
username=
password=
#set root of the additional mqtt client:
topicRoot=nspanel-bridge
#delay in seconds to try reconnect to server, if connection is lost:
reconnectDelay=5
#cycle time in seconds to publish changes in topics:
publishDelay=1
#Every publishcycle*fullPublishCycle will be all topics published even if no data changed:
fullPublishCycle=60
#nspanel command timeout. Time in seconds to wait until panel answers on commands witch "Done"
cmdTimeout=5
#brightness of the screensaver in %
screensaver=10
#standard brightness of the pages in %
standard=100
#screensaver timeout in seconds. 0 means no screensaver brighness change
saverTimeout=20
#sceensaver content update in minutes (to update the weather content). 0=Never
saverUpdate=30

[logging]
#configure the log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
level=INFO
#log file path
path=log
#log file name
file=nspanelMqttBridge.log

[oh]
#network address of the openhab instance including http:// or https://
host=http://192.168.1.31
#rest api port of openhab (Keep it 8080 for http and 8443 for https, if did not make changes in openhab standard config)
#port=8080
port=8080
#rest api port of openhab (Keep it empty, if did not make changes in openhab standard config)
apiKey=
#timeout for requests to the openHAB instance in seconds
timoeout=2

[panels]
#define a list of panesl in your home. You can configure more than one line here!
#Name before "="" must match to the name of one of the main page which you configured in .page files and will be the default page when leaving the screen saver for this panel
#Name after "=" must match to one of the configured nspanel mqtt topics in tasmota
#Additonally the used hmi can be specified by adding:
#hmi1 for hmi from https://github.com/joBr99/nspanel-lovelace-ui/tree/main/HMI
#hmi2 for hmi from https://github.com/ticaki/ioBroker.nspanel-lovelace-ui/tree/main/HMI
Flur=tasmota/NsPanel01,hmi1

[configPath]
#pathname to the pages definition files. Its recommended to put the folder in the openhab configuration folder
#to have easy access to the files and to have a common backup of all configuration files.
#Note: If the directory does not exist, it will be created when the bridge is started and you will find a readme file in this directory.
cards=/etc/openhab/nspanel_cards
#You can disable the yaml file observer. Than you need to restart the bridge by each change in the yaml files to apply the changes.
#This can be usefull if you have problems with the observer or if you want to have more control about when the changes are applied.
observer=enabled

[localize]
#language file
lang=lang/english.json
#lang=lang/english_US.json
#lang=lang/german.json

[skin]
#skin file
skinFile=skin/default_skin.json
