#
# This file contains an example of a notification card
#
cards:
  - name: BatteryAlarm #free name of the state card.
    type: popupNotify
    title: Batterie Warnung
    slots: #2 slots must be defined in a notify popup
      - class: ohItem #switch to activate the notification
        type: switch
        item: Switch_BatteryWarning
      - class: ohItem #Notification text item
        type: text
        item: M_BatteryWarning
  - name: PlantAlarm #free name of the state card.
    type: popupNotify
    fontSize: 1
    title: Pflanzen giessen!
    slots: #2 slots must be defined in a notify popup
      - class: ohItem #switch to activate the warning
        type: switch
        item: Switch_PlantWarning
        icon: palm-tree
        iconColor: green
      - class: ohItem #Warning text
        type: text
        item: String_PlantWarning 
