#
# Home cards
#
cards:
  - name: Test
    title: shutter test
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #All default
        type: shutter
        item: R_RolladenWintergarten
      - class: ohItem #Default with tilt function
        type: shutter
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
      - class: ohItem #Default with tilt function, shutter text, and shutter down disabeled
        type: shutter
        text: Wintergarten
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
      - class: ohItem #Everything defined
        type: shutter
        text: Wintergarten
        icon: \uefa2a 
        shutterControls: disable|enable|enable #optional setting for shutte up|stop| down buttons. Default is enable|enable|enable
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
        tiltControls: disable|enable|enable #optional setting for tilt up|stop| down buttons. Default is enable|enable|enable
  - name: Test2
    title: light test
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #All default: Light has just switch and label text is taken from openhab item
        type: light
        item: Switch_Kugellampe
      - class: ohItem #Light with dimmer function and icon
        type: light
        text: Kugel
        item: Switch_Kugellampe
        dimmerItem: Dimmer_Kugellampe
      - class: ohItem #Light with dimmer and color temperatur and special icon
        type: light
        text: Kugel smart
        icon: \ue6b4 #lamp
        item: Switch_Kugellampe
        dimmerItem: Dimmer_Kugellampe
        colTempItem: Dimmer_Kugellampe_Temp
      - class: ohItem #Everything defined
        type: light
        text: Kugel farbig
        icon: \ue6b4 #lamp
        item: Switch_Kugellampe
        dimmerItem: Dimmer_Kugellampe
        colTempItem: Dimmer_Kugellampe_Temp
        colorItem: Color_Kugellampe         #not supported yet!!
  - name: Test3
    title: Test switch/button
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #default switch text taken from openhab item label
        type: switch
        item: Switch_Kugellampe
      - class: ohItem #switch with test and special icon
        type: switch
        text: Kugel
        icon: \ue6b4 #lamp
        item: Switch_Kugellampe
      - class: ohItem #Default button with text taken from openhab item label
        type: button
        item: Switch_Kugellampe
      - class: ohItem #Button with text, special icon and color
        type: button
        text: Yamaha receiver
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaPower
  - name: Test4
    title: Test button/number
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #test oh string type as buttons. Label as text and options taken from openhab
        type: button
        item: YamahaInput
      - class: ohItem #test oh string as button. With text, options, icon and iconcolor defined
        type: button
        text: Receiver
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: ohItem #Default number
        type: number
        item: Dimmer_Kugellampe
      - class: ohItem #Number with text, special icon and color and min/max limit
        type: number
        text: Limited number
        icon: \ue6b4 #lamp
        iconColor: orange
        item: Dimmer_Kugellampe
        min: 10
        max: 50
  - name: Test5
    title: Test Text/Input Select
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #test oh string type as text. Label as text and options taken from openhab
        type: text
        item: YamahaInput
      - class: ohItem #test oh string as text. With text, options, icon and iconcolor defined
        type: text
        text: Receiver Info
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: ohItem #Default number
        type: input_sel
        item: YamahaInput
      - class: ohItem #Button with text, special icon and color
        type: input_sel
        text: Input select
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
  - name: Test6_noTitle #Card without title
    #title: Test Text/Input Select
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem
        type: openweathermap
        item: W_IconID_0
        textItem: W_Temperatur_0
        timeItem: W_Messung_0
      - class: ohItem #text with limited option list
        type: text
        text: Receiver Info
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: ohItem #Input select with limited option list
        type: input_sel
        text: Input select
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: navigate
        text: home
        icon: \uebaa
        iconColor: pink
        navTo: home/.
  - name: Test7 
    title: Test Grid unusual
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem
        type: openweathermap
        item: W_IconID_0
        textItem: W_Temperatur_0
        timeItem: W_Messung_0
      - class: ohItem #test oh string as text. With text, options (test options outside option list)
        type: text
        text: Receiver Info
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: ohItem #Button with text, special icon and color
        type: input_sel
        text: Input select
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: navigate
        text: Stay in test
        icon: \uebaa
        iconColor: pink
        navTo: test_saver/test5
      - class: navigate
        text: home
        icon: \uebaa
        iconColor: pink
        navTo: home/.
      - class: ohItem
        type: number
        item: Aussentemperatur
        icon: \ue503
        iconColor: lightgrey
  - name: Test8
    title: Grid item states
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem 
        type: text
        text: =itemState
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: ohItem #Button with text, special icon and color
        type: input_sel
        text: =itemState
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: ohItem
        type: number
        text: =itemState
        item: Aussentemperatur
        icon: \ue503
        iconColor: lightgrey
      - class: ohItem
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
      - class: ohItem
        type: light
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
      - class: ohItem
        type: button
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
  - name: Test9
    title: iconStateColor
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem
        type: light
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
        iconStateColor:
      - class: ohItem
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        iconColor: blue
        icon: \ue6b4
        iconColor: lightblue
        iconStateColor: True
      - class: ohItem
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
        iconStateColor:
      - class: ohItem
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
        iconStateColor: False
      - class: ohItem
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
        iconStateColor: Red
      - class: ohItem
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
        iconStateColor: red|orange
  - name: Test10
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem
        type: number
        text: =itemState
        item: Dimmer_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
        options: 0.0,10.0,20.0,30.0,40.0,100.0
