#
# Home cards
#
cards:
  - name: TestX
    title: shutter test
    group:  test ,  test_saver, _status_cards_
    type: cardEntities
    slots:
      - class: ohItem #All default
        type: shutter
        text: Meiner
        item: R_RolladenWintergarten
      - class: ohItem #Default with tilt function
        type: shutter
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
      - class: ohItem #Default with tilt function, shutter text, and shutter down disabeled
        type: shutter
        text: Wintergarten
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
      - class: ohItem #Everything defined
        type: shutter
        text: Wintergarten
        icon: \uefa2a 
        shutterControls: disable|enable|enable #optional setting for shutte up|stop| down buttons. Default is enable|enable|enable
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
        tiltControls: disable|enable|enable #optional setting for tilt up|stop| down buttons. Default is enable|enable|enable
      - class: ohItem #Default with tilt function, shutter text, and shutter down disabeled
        type: shutter
        text: Wintergarten
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
      - class: ohItem #Everything defined
        type: shutter
        text: Wintergarten
        icon: \uefa2a 
        shutterControls: disable|enable|enable #optional setting for shutte up|stop| down buttons. Default is enable|enable|enable
        item: R_RolladenWintergarten
        tiltItem: R_RolladenWintergarten #optional tilt item
        tiltControls: disable|enable|enable #optional setting for tilt up|stop| down buttons. Default is enable|enable|enable
  - name: Test2
    title: light test
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #All default: Light has just switch and label text is taken from openhab item
        type: light
        item: Switch_Kugellampe
      - class: ohItem #Light with dimmer function and icon
        type: light
        text: Kugel
        item: Switch_Kugellampe
        dimmerItem: Dimmer_Kugellampe
      - class: ohItem #Light with dimmer and color temperatur and special icon
        type: light
        text: Kugel smart
        icon: \ue6b4 #lamp
        item: Switch_Kugellampe
        dimmerItem: Dimmer_Kugellampe
        colTempItem: Dimmer_Kugellampe_Temp
      - class: ohItem #Everything defined
        type: light
        text: Kugel farbig
        icon: \ue6b4 #lamp
        item: Switch_Kugellampe
        dimmerItem: Dimmer_Kugellampe
        colTempItem: Dimmer_Kugellampe_Temp
        colorItem: Color_Kugellampe         #not supported yet!!
  - name: Test3
    title: Test switch/button
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #default switch text taken from openhab item label
        type: switch
        item: Switch_Kugellampe
      - class: ohItem #switch with test and special icon
        type: switch
        text: Kugel
        icon: \ue6b4 #lamp
        item: Switch_Kugellampe
      - class: ohItem #Default button with text taken from openhab item label
        type: button
        item: Switch_Kugellampe
      - class: ohItem #Button with text, special icon and color
        type: button
        text: Yamaha receiver
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaPower
  - name: Test4
    title: Test button/number
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #test oh string type as buttons. Label as text and options taken from openhab
        type: button
        item: YamahaInput
      - class: ohItem #test oh string as button. With text, options, icon and iconcolor defined
        type: button
        text: Receiver
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: ohItem #Default number
        type: number
        item: Dimmer_Kugellampe
      - class: ohItem #Number with text, special icon and color and min/max limit
        type: number
        text: Limited number
        icon: \ue6b4 #lamp
        iconColor: orange
        item: Dimmer_Kugellampe
        min: 10
        max: 50
  - name: Test5
    title: Test Text/Input Select
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem #test oh string type as text. Label as text and options taken from openhab
        type: text
        item: YamahaInput
      - class: ohItem #test oh string as text. With text, options, icon and iconcolor defined
        type: text
        text: Receiver Info
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: ohItem #Default number
        type: input_sel
        item: YamahaInput
      - class: ohItem #Button with text, special icon and color
        type: input_sel
        text: Input select
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
  - name: Test6_noTitle #Card without title
    #title: Test Text/Input Select
    group:  test ,  test_saver
    type: cardEntities
    slots:
      - class: ohItem
        type: openweathermap
        item: W_IconID_0
        textItem: W_Temperatur_0
        timeItem: W_Messung_0
      - class: ohItem #text with limited option list
        type: text
        text: Receiver Info
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: ohItem #Input select with limited option list
        type: input_sel
        text: Input select
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: navigate
        text: home
        icon: \uebaa
        iconColor: pink
        navTo: home/.
  - name: Test7 
    title: Test Grid
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem
        type: openweathermap
        item: W_IconID_0
        textItem: W_Temperatur_0
        timeItem: W_Messung_0
      - class: ohItem #test oh string as text. With text, options (test options outside option list)
        type: text
        text: Receiver Info
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: ohItem #Button with text, special icon and color
        type: input_sel
        text: Input select
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: navigate
        text: Stay in test
        icon: \uebaa
        iconColor: pink
        navTo: test_saver/test5
      - class: navigate
        text: home
        icon: \uebaa
        iconColor: pink
        navTo: home/.
      - class: ohItem
        type: number
        text: =itemState
        item: Aussentemperatur
        icon: \ue503
        iconColor: lightgrey
  - name: Test8
    title: Grid item states
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem 
        type: text
        text: =itemState
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: PHONO=Plattenspieler
      - class: ohItem #Button with text, special icon and color
        type: input_sel
        text: =itemState
        icon: \ueec4 #remote
        iconColor: orange
        item: YamahaInput
        options: TUNER=Radio,PHONO=Plattenspieler,AV1=PS3,AV2=vu2+,AV3,AV4,AV5=Port 5,AV6=AV6,Bluetooth=Bluetooth,USB=USB,NET RADIO=NET RADIO,AUDIO1=Fernseher
      - class: ohItem
        type: number
        text: =itemState
        item: Aussentemperatur
        icon: \ue503
        iconColor: lightgrey
      - class: ohItem
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
      - class: ohItem
        type: light
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
      - class: ohItem
        type: button
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
  - name: Test9
    title: icon/color state
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem #simple color, and icon
        type: light
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
      - class: ohItem #icon changes
        type: light
        text: =itemState
        item: Switch_Kugellampe
        icon: ON=\ue6b4,OFF=\uF7CF
        iconColor: lightblue
      - class: ohItem #icon and color changes
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: OFF=grey,ON=red
      - class: ohItem #color changes
        type: switch
        text: =itemState
        item: Switch_Kugellampe
        icon: \ue6b4
        iconColor: ON=red,OFF=orange
  - name: Test10
    group:  test ,  test_saver
    type: cardGrid
    slots:
      - class: ohItem
        type: number
        text: =itemState
        item: Dimmer_Kugellampe
        icon: \ue6b4
        iconColor: lightblue
        options: 0.0,10.0,20.0,30.0,40.0,100.0
  - name: Test11 #chart defaults
    group:  test ,  test_saver
    title: Test number chart
    type: cardChart
    slots:
      - class: ohItem
        type: number
        item: Stromzaehler_power
  - name: Test12 #chart color defefine no period
    group:  test ,  test_saver
    title: Test state chart
    type: cardChart
    life: true
    #period: d
    #past: w
    color: yellow
    slots:
      - class: ohItem
        type: switch
        item: Switch_Kugellampe
  - name: Test13 #chart color defefine period 1 day
    group:  test ,  test_saver
    title: Test state chart2
    type: cardChart
    life: true
    period: d
    #past: w
    color: blue
    slots:
      - class: ohItem
        type: input_sel
        item: YamahaInput
  - name: Test13x #chart color defefine period 1 day week ago
    group:  test ,  test_saver
    title: Test state chart3 X
    type: cardChart
    life: true
    period: d
    past: w
    color: blue
    slots:
      - class: ohItem
        type: input_sel
        item: YamahaInput
  - name: Test14 #chart current day and color defined
    group:  test ,  test_saver
    title: Test number chart X
    type: cardChart
    life: true
    period: d
    #past: w
    slots:
      - class: ohItem
        type: number
        item: Stromzaehler_power
  - name: Test15 #chart one day and color defined
    group:  test ,  test_saver
    title: Test number chart Y
    type: cardChart
    life: true
    period: d
    past: w
    color: red
    slots:
      - class: ohItem
        type: number
        item: Stromzaehler_power
  - name: Test16 #chart one day two nonth ago and color defined
    group:  test ,  test_saver
    title: Test number chart Z
    type: cardChart
    life: false
    period: d
    past: 2m
    color: blue
    slots:
      - class: ohItem
        type: number
        item: Stromzaehler_power
  - name: Test17 #chart one day two nonth ago and color defined
    group:  test ,  test_saver
    title: Test number chart 3
    type: cardChart
    life: false
    period: d
    past: 2m
    color: blue
    slots:
      - class: ohItem
        type: number
        item: Aussentemperatur
  - name: Test18 #chart color defefine period 2 weeks
    group:  test ,  test_saver
    title: Test state chart
    type: cardChart
    life: true
    period: 2w
    color: pink
    slots:
      - class: ohItem
        type: switch
        item: Switch_Kugellampe
  - name: Test19 #chart color defefine period 1 day week ago
    group:  test ,  test_saver
    title: Test state chart3
    type: cardChart
    life: true
    period: d
    past: w
    color: blue
    slots:
      - class: ohItem
        type: input_sel
        item: YamahaInput
  - name: Test20 #test cardPower
    group:  test ,  test_saver
    title: Test cardPower
    type: cardPower
    slots:
      - class: ohItem
        type: number
        icon: home
        iconColor: green
        item: Stromzaehler_power
      - class: ohItem
        type: number
        item: Stromzaehler_power
      - class: ohItem
        type: number
        speed: -20
        text: Solar 1
        icon: solar-power-variant
        iconColor: yellow
        item: Stromzaehler_power
      - class: ohItem
        type: number
        text: Car port 1
        icon: car-electric
        iconColor: blue
        speed: 20
        item: Stromzaehler_power
      - class: ohItem
        type: number
        text: Car port 2
        icon: car-electric
        iconColor: blue
        speed: 100
        item: Stromzaehler_power
      - class: ohItem
        type: number
        text: Solar 2
        icon: solar-power-variant
        iconColor: yellow
        speed: 20
        item: Stromzaehler_power
      - class: ohItem
        type: number
        text: Car port 3
        icon: car-electric
        iconColor: blue
        speed: -50
        item: Stromzaehler_power
      - class: ohItem
        type: number
        text: Car port 4
        icon: car-electric
        iconColor: blue
        speed: -10
        item: Stromzaehler_power
